name: release
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Bump version on merging Pull Requests with specific labels. (bump:major,bump:minor,bump:patch)
      # - uses: haya14busa/action-bumpr@v1
      # test 1
      # - uses: haya14busa/action-bumpr@sign-tag
      #   with:
      #     sign_tags: true
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
