name: Call Hello World Workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
    inputs:
      custom_name:
        description: 'Custom name to greet'
        required: false
        default: 'GitHub Actions'

jobs:
  call-reusable-local:
    uses: ./.github/workflows/hello-world-reusable.yml
    with:
      name: ${{ inputs.custom_name || 'local' }}
    # secrets:
    #   example_secret: ${{ secrets.MY_SECRET }}
    #
  call-reusable:
    uses: haya14busa/github-actions-playground/.github/workflows/hello-world-reusable.yml@master
    with:
      name: ${{ inputs.custom_name || 'remote' }}
    # secrets:
    #   example_secret: ${{ secrets.MY_SECRET }}
