name: playground
on:
  push:
  pull_request:
    # types:
    #   - closed
    #   - labeled
  issues:
    types:
      - labeled
jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub Event
        run: cat "${GITHUB_EVENT_PATH}"

      - name: Dump Env
        run: env

      - name: Dump IP
        run: curl https://httpbin.org/ip

      - uses: ./.github/actions/reviewdog-install
      - name: check reviewdog version
        run: reviewdog -version

      - uses: ./.github/actions/reviewdog-install
        with:
          reviewdog_version: nightly
      - name: check reviewdog version
        run: reviewdog -version

      - name: merged event
        if: github.event.pull_request.merged
        run: echo "pull_request.merged event!"

      - run: git show
      - run: echo "GITHUB_WORKSPACE:${GITHUB_WORKSPACE}"
      - run: echo "GITHUB_ACTION:${GITHUB_ACTION}"
      - run: echo "GITHUB_ACTIONS:${GITHUB_ACTIONS}"

      - run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo hello > ${{ github.workspace }}/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: playground-artifact
          path: ${{ github.workspace }}/artifact/**/*

      - name: Check scope
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -I -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com
          curl -I -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/rate_limit
