name: playground
on:
  push:
  pull_request:
        types: [closed]
jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub Event
        run: cat "${GITHUB_EVENT_PATH}"

      - name: Dump Env
        run: env

      - name: Dump IP
        run: curl https://httpbin.org/ip

      - name: merged event
        if: github.event.pull_request.merged
        run: echo "pull_request.merged event!"

      - run: git show
