name: playground
on:
  push:
    # branches:
    #   - main
  pull_request:
    # types:
    #   - closed
    #   - labeled
  issues:
    types:
      - labeled
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub Event
        run: cat "${GITHUB_EVENT_PATH}"

      - name: Dump Env
        run: env

      - name: Dump IP
        run: curl https://httpbin.org/ip

      - name: Default branch
        run: echo ${{ github.event.repository.default_branch }}

      - name: merged event
        if: github.event.pull_request.merged
        run: echo "pull_request.merged event!"

      - run: git show
      - run: echo "GITHUB_WORKSPACE:${GITHUB_WORKSPACE}"
      - run: echo "GITHUB_ACTION:${GITHUB_ACTION}"
      - run: echo "GITHUB_ACTIONS:${GITHUB_ACTIONS}"

      - run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo hello > ${{ github.workspace }}/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: playground-artifact
          path: ${{ github.workspace }}/artifact/**/*

      - uses: jenseng/dynamic-uses@v1
        with:
          # now you can use expressions 🥳
          uses: actions/setup-node@${{ 'v4' }}
          # the `with` needs to be converted to a valid json string
          with: '{ "node-version": 18 }'
