name: playground
on:
  push:
    # branches:
    #   - main
  pull_request:
    # types:
    #   - closed
    #   - labeled
  issues:
    types:
      - labeled
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub Event
        run: cat "${GITHUB_EVENT_PATH}"

      - name: Dump Env
        run: env

      - name: Dump IP
        run: curl https://httpbin.org/ip

      - name: Default branch
        run: echo ${{ github.event.repository.default_branch }}

      - name: merged event
        if: github.event.pull_request.merged
        run: echo "pull_request.merged event!"

      - run: git show
      - run: echo "GITHUB_WORKSPACE:${GITHUB_WORKSPACE}"
      - run: echo "GITHUB_ACTION:${GITHUB_ACTION}"
      - run: echo "GITHUB_ACTIONS:${GITHUB_ACTIONS}"

      - run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo hello > ${{ github.workspace }}/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: playground-artifact
          path: ${{ github.workspace }}/artifact/**/*

      - name: Check scope
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -I -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com
          curl -I -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/rate_limit
      - name: Check repo scope (haya14busa/github-actions-playground)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/haya14busa/github-actions-playground

      - name: Check repo scope (reviewdog/reviewdog)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/reviewdog/reviewdog
