name: post_pull_request
on:
  workflow_run:
    workflows: ["playground"]
    types:
      - completed

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub Event
        run: cat "${GITHUB_EVENT_PATH}"

      - name: Dump Env
        run: env

      - name: Dump IP
        run: curl https://httpbin.org/ip

      - run: git show
      - run: echo "GITHUB_WORKSPACE:${GITHUB_WORKSPACE}"

      - uses: actions/download-artifact@v2
        with:
          name: playground-artifact

      - name: Display structure of downloaded files
        run: ls -R
      - run: cat world.txt
